### ISSUE TITLE
Regression in CreateStorageKey

### ISSUE THREAD

**Issue by vgeddes** [centrifuge/go-substrate-rpc-client#168] opened 2021-06-18 12:42 UTC
We are users of GSRPC (and contributors too) in https://github.com/Snowfork/polkadot-ethereum. The new API for CreateStorageKey breaks compatibility. But it also includes a regression:

Suppose I have a single storage item 'MyPallet.Nonce'. It is a not a map or a double-map. However calling `types.CreateStorageKey(metadata, "MyPallet", "Nonce")` fails with:
```
Nonce is a map, therefore requires precisely one argument. received: 0
```

So to get it to work I have to pass `nil` like this, which is confusing, since Nonce is very certainly not a map:
```
types.CreateStorageKey(metadata, "MyPallet", "Nonce", nil)
```

**Comment by ThreeAndTwo** [comment] 2021-06-18 17:55
same error. those demos exist error in https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client/v3，because v13 for CreateStorageKey breaks compatibility.

**Comment by vedhavyas** [comment] 2021-06-18 18:18
I'm reverting the breaking change, keeping the metadata v13  make a release in a bit. Thank you!

**Comment by vedhavyas** [comment] 2021-06-18 18:24
Sorry about this 🙏🏼

**Comment by ParthDesai** [comment] 2021-06-21 01:44
@vgeddes @vedhavyas I have fixed CreateStorageKey to be backward compatible.

**Comment by ParthDesai** [comment] 2021-06-21 05:38
@vedhavyas @vgeddes  I have also added comprehensive test cases to make sure I have fixed any regression. PR: #169

**Comment by ParthDesai** [comment] 2021-06-21 05:40
@vgeddes @vedhavyas  PR: #169 adds comprehensive test cases for `CreateStorageKey`.

**Comment by vedhavyas** [comment] 2021-06-21 07:59
@vgeddes @ThreeAndTwo can you confirm if the regression is fixed with the PR above ?

**Comment by ParthDesai** [comment] 2021-06-21 08:46
> @vgeddes @ThreeAndTwo can you confirm if the regression is fixed with the PR above ?

@vedhavyas The regression was already fixed via PR: #166 
But, it was not covered by tests. PR: #169 aims to cover the new changes made in `CreateStorageKey` with tests.

**Comment by ThreeAndTwo** [comment] 2021-06-21 10:03
@vedhavyas @ParthDesai I tested it. CreateStorageKey is normal, but I find decimal have inaccurate for token.
current balance: 855.359271
before balance: 8.55359271
in fact balance: 8.55359271

**Comment by ParthDesai** [comment] 2021-06-21 10:07
> @vedhavyas @ParthDesai I tested it. CreateStorageKey is normal, but I find decimal have inaccurate for token.
> current balance: 855.359271
> before balance: 8.55359271
> in fact balance: 8.55359271

This may not be related to `CreateStorageKey` at all.

**Comment by vedhavyas** [comment] 2021-06-21 10:11
> This may not be related to CreateStorageKey at all.

True.

@ThreeAndTwo double check your type please. Its usually the case

**Comment by vedhavyas** [comment] 2021-06-21 10:16
closing this since its confirmed to be fixed in latest patch.

@ThreeAndTwo please open an new issue if the above mentioned decimal issue still exists.

**Closed by vedhavyas** 2021-06-21 10:16 UTC

**Comment by ThreeAndTwo** [comment] 2021-06-21 10:21
yeah, everything is ok, thx.
