### ISSUE TITLE
Assets.create call param types

### ISSUE THREAD

**Issue by freddyli7** [centrifuge/go-substrate-rpc-client#280] opened 2022-07-13 22:10 UTC
hey guys, so now I know that this `wasm unreachable issue` is because the param type of the tx is wrong, and I'm having the same issue now when sending `Assets.create` call on the parachain, the doc is saying that type should be `create(id: Compact<u32>, admin: MultiAddress, min_balance: u128)`, and I followed that, but it didn't work, I have a feeling that I'm using the wrong type but don't know what the correct types are. Below this how I construct the tx call:

```Go
func CreateAsset(rpcEndpoint string, sender signature.KeyringPair) {
	api, err := gsrpc.NewSubstrateAPI(rpcEndpoint)
	if err != nil {
		panic(err)
	}

	meta, err := api.RPC.State.GetMetadataLatest()
	if err != nil {
		panic(err)
	}

	admin, err := types.NewMultiAddressFromHexAccountID("0x266ac8deb3ef61389b59d3a242e586e0a742ad84ba7398f39cef6131521e1457") // TEST4 account
	if err != nil {
		panic(err)
	}

        // assetId := types.NewU32(9898) // I tried this type too, no luck
	assetId := types.NewUCompactFromUInt(9898)             // type should be Compact<u32> according to the doc
	minBalance := types.NewU128(*big.NewInt(1000000000000)) // type should be u128 according to the doc

	c, err := types.NewCall(meta, "Assets.create", assetId, admin, minBalance)
	if err != nil {
		panic(err)
	}

	ext := types.NewExtrinsic(c)

	genesisHash, err := api.RPC.Chain.GetBlockHash(0)
	if err != nil {
		panic(err)
	}

	rv, err := api.RPC.State.GetRuntimeVersionLatest()
	if err != nil {
		panic(err)
	}

	key, err := types.CreateStorageKey(meta, "System", "Account", sender.PublicKey)
	if err != nil {
		panic(err)
	}

	var accountInfo types.AccountInfo
	ok, err := api.RPC.State.GetStorageLatest(key, &accountInfo)
	if err != nil || !ok {
		panic(err)
	}

	options := types.SignatureOptions{
		BlockHash:          genesisHash,
		Era:                types.ExtrinsicEra{IsMortalEra: false},
		GenesisHash:        genesisHash,
		Nonce:              types.NewUCompactFromUInt(uint64(accountInfo.Nonce)),
		SpecVersion:        rv.SpecVersion,
		Tip:                types.NewUCompactFromUInt(0),
		TransactionVersion: rv.TransactionVersion,
	}

	err = ext.Sign(sender, options)
	if err != nil {
		panic(err)
	}

	hash, err := api.RPC.Author.SubmitExtrinsic(ext)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Tx sent with hash %#x\n", hash)
}
```

The doc I'm referring to is [here](https://polkadot.js.org/docs/substrate/extrinsics/#createid-compactu32-admin-multiaddress-min_balance-u128)

The error I got is:
![image](https://user-images.githubusercontent.com/13714909/178845018-71a881e0-b62f-4067-a18d-8a668935bb78.png)

**Comment by freddyli7** [comment] 2022-07-14 15:55
I'm running a local network with relay chain and parachain, both version are `v0.9.23`
polkadot relay chain node binary from here: https://github.com/paritytech/polkadot
parachain node binary from here: https://github.com/paritytech/cumulus

**Comment by cdamian** [comment] 2022-07-15 11:45
@freddyli7 Can you trying using `U64` for the balance? Cumulus has a different type for balance based on - https://github.com/paritytech/cumulus/blob/v0.9.230/parachains/runtimes/testing/rococo-parachain/src/lib.rs#L490

**Comment by freddyli7** [comment] 2022-07-15 18:33
@cdamian tried with `minBalance := types.NewU64(1000000000000)`, got Invalid Transaction error when calling `SubmitExtrinsic`

**Comment by cdamian** [comment] 2022-07-18 05:14
@freddyli7 can you try creating the extrinsic using https://polkadot.js.org/apps/#/explorer to see if you get the same error? 

Also, did you start your local setup using the guide described here - https://github.com/paritytech/cumulus/blob/polkadot-v0.9.23/README.md#local-setup ?

**Comment by freddyli7** [comment] 2022-07-18 15:35
hey @cdamian, I tried on UI of `polkadot.js.org/app` and also tried writing some js code integrating with `@polkadot/api` lib, both work fine for all `assets` related extrinsic calls against my local network. 

Yes that is what I followed to setup the local network, also on my local network, both relay chain and parachain are producing blocks without issues, and I also managed to register the parachain onto the relay chain as well.

I can even create new asset from the UI and query metaData of it from js code.

the version of `@polkadot/api` is `v8.11.3`

**Comment by cdamian** [comment] 2022-07-21 08:35
@freddyli7 I did more testing and it doesn't seem to be related to the eras, the UI is able to send transaction with both immortal and mortal eras without any errors. I will keep checking this out when time allows and get back to you.

**Comment by mikiquantum** [comment] 2022-07-29 01:38
@freddyli7 The issue is that the cumulus runtime doesn't validate the TransactionVersion as extra signed payload parameter. 

GSRPC default behavior is to use the latest ExtrinsicSignatureV4 payload which contains this parameter. Therefore that cumulus parachain cannot validate the signature because it is reconstructing it with a different payload than what it was originally sent by the client. 
It seems to me that it was an oversight to add this extra check `frame_system::CheckTxVersion<Runtime>,` in the cumulus extra signed block https://github.com/paritytech/cumulus/blob/9f5d8c333a245c847897829756f2aafee71fae6a/parachains/runtimes/testing/rococo-parachain/src/lib.rs#L570 
If that line is added then your test would work. 

Alternatively, if you need to use a target chain that behaves as such, you would need to create your own custom `sign` function for a non default/compatible chain that only uses `ExtrinsicPayloadV3` like the one here https://github.com/centrifuge/go-substrate-rpc-client/blob/17e1c01f31aa630c0df50d3fde42c19df6efb79b/types/extrinsic.go#L138 

Additionally, you would need to modify the `minBalance` that you pass to the create to be U64, instead of U128:
`minBalance := types.NewU64(1000000000000)`

**Comment by mikiquantum** [comment] 2022-07-29 16:48
@freddyli7 This PR has been merged: https://github.com/paritytech/cumulus/pull/1483 Feel free to pull down the latest cumulus and rebuild your parachain locally. Closing this for now, please reopen if issue persists.

**Closed by mikiquantum** 2022-07-29 16:48 UTC
