### ISSUE TITLE
Problem about events decoding

### ISSUE THREAD

**Issue by wangjj9219** [centrifuge/go-substrate-rpc-client#141] opened 2021-04-01 10:53 UTC
Hi guys, I need help. I'm using ChainSafe/ChainBridge and encounter an error originated from centrifuge/go-substrate-rpc-client, the error msg is: "unable to find field Currencies_Transferred for event #4 with EventID [6 0]"

I scan the code: https://github.com/centrifuge/go-substrate-rpc-client/blob/904cb0b931a9949b08e731fa14c24ed62226a748/types/event_record.go#L285-L288 ,
it seems an error when decoding events. And I found that only when decoding those events which contain type CurrencyId will occur this error. Type CurrencyId is a complex enum type that defined on Acala. Where should I define how to decode type CurrencyId?

And I see these definations: https://github.com/centrifuge/go-substrate-rpc-client/blob/master/types/events.go ,
ChainBridge also defines its events: https://github.com/ChainSafe/ChainBridge/blob/main/shared/substrate/events.go
Do I have to register all events that appear in Acala's metadata like this?

**Comment by wangjj9219** [comment] 2021-04-05 11:09
Version info: 
substrate - v3.0.0 
gsrc - latest version

These's an event that include an enum type on my Substrate chain:
```
enum Status {
	Off,
	On,
} 

// This event includes a enum type
Test1(Status)
```

And I defined event type in go side:
```
// type definition
type Status struct {
	IsOff 	bool
	IsOn 	bool
}

// impl Decode for this type
func (m *Status) Decode(decoder scale.Decoder) error {
	b, err := decoder.ReadOneByte()
	if err != nil {
		return err
	}

	if b == 0 {
		m.IsOff = true
	} else if b == 1 {
		m.IsOn = true
	}

	return nil
}

// event definition
type EventTestModuleTest1 struct {
	Phase           types.Phase
	Status          Status
	Topics          []types.Hash
}

// registor this event to Events struct
type Events struct {
	types.EventRecords
	TestModule_Test1        []EventTestModuleTest1
}

// process code:
var records types.EventRecordsRaw
e := Events{}
err = records.DecodeEventRecords(&meta, &e)
```

I triggered event Test1(On) on substrate, `DecodeEventRecords` function threw this error:` could not be decoded field by field, error: unexpected EOF`.
I scanned the log, `Phase`, `EventId` were decoded correctly, and I checked the raw event records buff:`[16 0 0 0 0 0 0 0 80 149 162 9 0 0 0 0 2 0 0 0 1 0 0 0 41 2 1 0 0 1 0 0 0 55 0 0 0 0 1 0 0 0 0 0 32 78 0 0 0 0 0 0 0 0 0]`,  exclude the slices of `Phase` , `EventId`and `Topics`, the slice of field is on prefix `[26:27]` (ie. [1] , 1 byte represents `Status::On`).

Then I changed the field definition of `Status` into `uint8/byte` and triggered again:
```
type EventTestModuleTest1 struct {
	Phase           types.Phase
	Status          uint8
	Topics          []types.Hash
}
```

this time, everything's ok, there's no error. 

I think that my implementation for decoding `Status` is correct. And I scanned the code snippets related to the remaining fields decoding and tried to find out the reason:
https://github.com/centrifuge/go-substrate-rpc-client/blob/904cb0b931a9949b08e731fa14c24ed62226a748/types/event_record.go#L284-L323 ,  but the reflect feature of Go is strange to me.  I think ur guys can reproduce this error and help me find the reason.

**Comment by vedhavyas** [comment] 2021-04-15 08:27
@wangjj9219

**Comment by vedhavyas** [comment] 2021-04-15 08:27
> Do I have to register all events that appear in Acala's metadata like this?

**Comment by vedhavyas** [comment] 2021-04-15 08:32
@wangjj9219 your enum types looks good on top. Can you send me the some encoded data to reproduce this ?

**Comment by wangjj9219** [comment] 2021-04-21 10:49
> @wangjj9219 your enum types looks good on top. Can you send me the some encoded data to reproduce this ?

raw events:
```
[16 0 0 0 0 0 0 0 80 149 162 9 0 0 0 0 2 0 0 0 1 0 0 0 7 0 0 1 212 53 147 199 21 253 211 28 97 20 26 189 4 169 159 214 130 44 133 88 133 76 205 227 154 86 132 231 165 109 162 125 28 189 45 67 83 10 68 112 90 208 136 175 49 62 24 248 11 83 239 22 179 97 119 205 75 119 184 70 242 165 240 124 0 32 74 169 209 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 10 6 59 60 120 82 5 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 72 78 48 52 0 0 0 0 0 0 0]
```

the events definition: https://github.com/AcalaNetwork/ChainBridge/blob/main/shared/acala/events.go

the result decoded by polkadot.js:
```
[
  {
    "phase": {
      "ApplyExtrinsic": "0"
    },
    "event": {
      "method": "ExtrinsicSuccess",
      "section": "system",
      "index": "0x0000",
      "data": [
        {
          "weight": "161,650,000",
          "class": "Mandatory",
          "paysFee": "Yes"
        }
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "ApplyExtrinsic": "1"
    },
    "event": {
      "method": "Transferred",
      "section": "currencies",
      "index": "0x0700",
      "data": [
        {
          "Token": "AUSD"
        },
        "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
        "5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL",
        "2.0000 Unit"
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "ApplyExtrinsic": "1"
    },
    "event": {
      "method": "Deposit",
      "section": "acalaTreasury",
      "index": "0x0a06",
      "data": [
        "22.8584 mUnit"
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "ApplyExtrinsic": "1"
    },
    "event": {
      "method": "ExtrinsicSuccess",
      "section": "system",
      "index": "0x0000",
      "data": [
        {
          "weight": "875,581,000",
          "class": "Normal",
          "paysFee": "Yes"
        }
      ]
    },
    "topics": []
  }
]
```

But use `DecodeEventRecords` to decode raw events, still report error when decode event `EventCurrenciesTransferred` 

This is our testnet console: https://apps-qwer951123.vercel.app/?rpc=wss%3A%2F%2Facala-testnet-1.polkawallet.io%3A9904%2F#/extrinsics   , event `Currencies_Transferred` triggered by extrinsic `currencies::Transfer` , and account `//Alice` has some test tokens.

**Comment by vedhavyas** [comment] 2021-04-21 11:14
@wangjj9219 looks like you are using different versions of gsrpc. I could see that you are using v1, v2 of gsrpc. That could be a problem. I just tried to listen for currency transferred events and transferred some tokens from Alice. Evrything worked. here is the code I have used

```
package main

import (
	"fmt"

	gsrpc "github.com/centrifuge/go-substrate-rpc-client/v3"
	"github.com/centrifuge/go-substrate-rpc-client/v3/scale"
	"github.com/centrifuge/go-substrate-rpc-client/v3/types"
)

func main() {
	api, err := gsrpc.NewSubstrateAPI("wss://acala-testnet-1.polkawallet.io:9904")
	if err != nil {
		panic(err)
	}

	meta, err := api.RPC.State.GetMetadataLatest()
	if err != nil {
		panic(err)
	}

	// Subscribe to system events via storage
	key, err := types.CreateStorageKey(meta, "System", "Events", nil, nil)
	if err != nil {
		panic(err)
	}

	sub, err := api.RPC.State.SubscribeStorageRaw([]types.StorageKey{key})
	if err != nil {
		panic(err)
	}
	defer sub.Unsubscribe()

	// outer for loop for subscription notifications
	for {
		set := <-sub.Chan()
		// inner loop for the changes within one of those notifications
		for _, chng := range set.Changes {
			if !types.Eq(chng.StorageKey, key) || !chng.HasStorageData {
				// skip, we are only interested in events with content
				continue
			}

			// Decode the event records
			events := Events{}
			err = types.EventRecordsRaw(chng.StorageData).DecodeEventRecords(meta, &events)
			if err != nil {
				panic(err)
			}

			for _, ct := range events.Currencies_Transferred {
				fmt.Println(ct.To, ct.From, ct.Amount, ct.Currency)
			}
		}
	}
}

type TokenSymbol = uint8
type EvmAddress = [20]byte

type DEXShare struct {
	IsToken bool
	AsToken TokenSymbol
	IsERC20 bool
	AsERC20 EvmAddress
}

func (p *DEXShare) Decode(decoder scale.Decoder) error {
	b, err := decoder.ReadOneByte()
	if err != nil {
		return err
	}

	switch b {
	case 0:
		p.IsToken = true
		err = decoder.Decode(&p.AsToken)
	case 1:
		p.IsERC20 = true
		err = decoder.Decode(&p.AsERC20)
	}

	if err != nil {
		return err
	}

	return nil
}

func (p DEXShare) Encode(encoder scale.Encoder) error {
	var err1, err2 error

	switch {
	case p.IsToken:
		err1 = encoder.PushByte(0)
		err2 = encoder.Encode(p.AsToken)
	case p.IsERC20:
		err1 = encoder.PushByte(2)
		err2 = encoder.Encode(p.AsERC20)
	}

	if err1 != nil {
		return err1
	}
	if err2 != nil {
		return err2
	}

	return nil
}

type CurrencyId struct {
	IsToken    bool
	AsToken    TokenSymbol
	IsDEXShare bool
	AsDEXShare struct {
		Share_0 DEXShare
		Share_1 DEXShare
	}
	IsERC20             bool
	AsERC20             EvmAddress
	IsChainSafeResource bool
	AsChainSafeResource [20]byte
}

func (p *CurrencyId) Decode(decoder scale.Decoder) error {
	b, err := decoder.ReadOneByte()
	if err != nil {
		return err
	}

	switch b {
	case 0:
		p.IsToken = true
		err = decoder.Decode(&p.AsToken)
	case 1:
		p.IsDEXShare = true
		err = decoder.Decode(&p.AsDEXShare)
	case 2:
		p.IsERC20 = true
		err = decoder.Decode(&p.AsERC20)
	case 3:
		p.IsChainSafeResource = true
		err = decoder.Decode(&p.AsChainSafeResource)
	}

	if err != nil {
		return err
	}

	return nil
}

func (p CurrencyId) Encode(encoder scale.Encoder) error {
	var err1, err2 error

	switch {
	case p.IsToken:
		err1 = encoder.PushByte(0)
		err2 = encoder.Encode(p.AsToken)
	case p.IsDEXShare:
		err1 = encoder.PushByte(1)
		err2 = encoder.Encode(p.AsDEXShare)
	case p.IsERC20:
		err1 = encoder.PushByte(2)
		err2 = encoder.Encode(p.AsERC20)
	case p.IsChainSafeResource:
		err1 = encoder.PushByte(2)
		err2 = encoder.Encode(p.AsChainSafeResource)
	}

	if err1 != nil {
		return err1
	}
	if err2 != nil {
		return err2
	}

	return nil
}

type EventCurrenciesTransferred struct {
	Phase    types.Phase
	Currency CurrencyId
	From     types.AccountID
	To       types.AccountID
	Amount   types.U128
	Topics   []types.Hash
}

type EventCdpEngineGlobalStabilityFeeUpdated struct {
	Phase  types.Phase
	Rate   types.U128
	Topics []types.Hash
}

type EventCdpTreasuryCollateralAuctionMaximumSizeUpdated struct {
	Phase    types.Phase
	Currency CurrencyId
	Topics   []types.Hash
}

type Events struct {
	types.EventRecords
	Currencies_Transferred                          []EventCurrenciesTransferred                          //nolint:stylecheck,golint
	AcalaTreasury_Deposit                           []types.EventTreasuryDeposit                          //nolint:stylecheck,golint
	CdpEngine_GlobalStabilityFeeUpdated             []EventCdpEngineGlobalStabilityFeeUpdated             //nolint:stylecheck,golint
	CdpTreasury_CollateralAuctionMaximumSizeUpdated []EventCdpTreasuryCollateralAuctionMaximumSizeUpdated //nolint:stylecheck,golint
}
```

**Comment by vedhavyas** [comment] 2021-04-22 10:46
Closing this for now. Please open this if you are seeing the issue with the latest version of gsrpc

**Closed by vedhavyas** 2021-04-22 10:46 UTC
