### ISSUE TITLE
getBlock() method sometimes failed in Polkadot

### ISSUE THREAD

**Issue by RJman-self** [centrifuge/go-substrate-rpc-client#151] opened 2021-04-22 13:02 UTC
It works well in kusama and westend,  and it's okay most of the time in polkadot, but sometimes the getBlock() meet error, I have to skip it.

The error can be reproduced, The error can reappear, please check Polkadot block#4744169

![image](https://user-images.githubusercontent.com/44558375/115717895-32b00c00-a3ad-11eb-97bf-4a295766246b.png)

```go
api, _ := gsrpc.NewSubstrateAPI(url)

hash, err := api.RPC.Chain.GetBlockHash(4744169)
if err != nil {
	fmt.Printf("GetBlockHash err\n")
}

block, err := api.RPC.Chain.GetBlock(hash)
if err != nil {
	fmt.Printf("Get Block err\n")
}

if block != nil {
	currentBlock := int64(block.Block.Header.Number)
	fmt.Printf("block is %v\n", currentBlock)
}
```

**Comment by vedhavyas** [comment] 2021-04-22 13:10
@RJman-self I'm able to fetch the block with following code
```

package main

import (
	"fmt"

	gsrpc "github.com/centrifuge/go-substrate-rpc-client/v3"
)

func main() {
	api, err := gsrpc.NewSubstrateAPI("wss://rpc.polkadot.io")
	checkErr(err)

	hash, err := api.RPC.Chain.GetBlockHash(4744169)
	if err != nil {
		fmt.Printf("GetBlockHash err\n")
	}

	block, err := api.RPC.Chain.GetBlock(hash)
	checkErr(err)

	fmt.Println(block.Block.Header.Number, len(block.Block.Extrinsics))
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}
```

Please ensure you use the latest master. Closing this as this is working as intended

**Closed by vedhavyas** 2021-04-22 13:10 UTC
